# Database credentials
database:
  # antingen denna
  file: "databasen.sqlite" 
  # eller alla dessa (om file är blankt)
  sql-user: "test"            #
  sql-pass: "test"
  sql-server: "127.0.0.1"
  sql-database: "SupportSystem"
  sql-port: 3306

redis:
  server: "localhost:6379"

sso:
  clientId:  "StudentPortal"
  clientSecret:  "EM4WKTSRUXVWG5RBTXC3VPOBTMF5Y3SL"
  baseAddress:  "https://localhost:44375/"
  backBaseAddress: "https://localhost:8080/"